### ISSUE TITLE
[Feature Request] Release kalidokit with types

### ISSUE THREAD

**Issue by YunYouJun** [yeemachine/kalidokit#12]
I install kalidokit by npm. And can not find types for it.

![image](https://user-images.githubusercontent.com/25154432/144549361-eacc35bf-1b1a-4fe8-8a09-3aec7d1272e8.png)

But i clone this repo and build it myself. I find inde.d.ts, etc. (by `tsc`)

![image](https://user-images.githubusercontent.com/25154432/144549429-8b74191e-2715-47e3-a065-c053273ee04a.png)

Did you forget to re-release the new version?

**Comment by yeemachine** [comment]
I haven't released the TS migration yet onto npm. Want to do a couple more tests first but I've been a bit busy lately. Prob another week before I update.

**Comment by tom-xingshuo** [comment]
> I haven't released the TS migration yet onto npm. Want to do a couple more tests first but I've been a bit busy lately. Prob another week before I update.

I like you!

**Comment by YunYouJun** [comment]
How to post it on @next tag? Just like `kalidokit@next`, I can help you with a test check.

**Comment by AlenSaito1** [comment]
@YunYouJun you can install the package directly from Github

```sh
npm i github:yeemachine/kalidokit
```

**Comment by yeemachine** [comment]
I've published KalidoKit with types to NPM. Should be the latest version `1.1.2`.
 #8
