### ISSUE TITLE
parse js files from project structure

### ISSUE THREAD

**Issue by ubilrodriguez** [yeemachine/kalidokit#16]
Excuse me I have a question in the docs capertar in the script.js file can't export any functions or new functions within that script.js file, when I want to use in another js file, the question is why is it? can't you export those functions from that script.js file?

**Comment by AlenSaito1** [comment]
You're not supposed to use the files inside the `docs` directory. You should be importing the methods from the package installed from [NPM](https://www.npmjs.com/package/kalidokit) or via [CDN](https://cdn.jsdelivr.net/npm/kalidokit@1.1/dist/kalidokit.umd.js")

**Comment by ubilrodriguez** [comment]
Let me understand in the open docs the files, I can't use within that if I should not make a separate folder in the same direction as the open docs?

**Comment by ubilrodriguez** [comment]
Excuse me, is your project developed in react and laravel? Or else in what exactly framework is it developed?

**Comment by ubilrodriguez** [comment]
> Como dijo Alen. Esta es una biblioteca destinada a ser importada a través de NPM o mediante una etiqueta de secuencia de comandos estándar de la CDN. Esto se escribió en JavaScript simple y luego se migró a Type

so script.js is a library? that you have developed because inside that script.js file there is a function.

const camera = new Camera (videoElement, {
     onFrame: async () => {
         await holistic.send ({image: videoElement});
     },
     width: 640,
     height: 480,
});
I want this function used in another .js file, to be placed in a button of accessor to turn on the camera.

the problem that scrupt.js won't let me extract those functions

**Comment by yeemachine** [comment]
Script.js is not the library. It is used for testing the KalidoKit library which is found in the dist folder once you build the project. 

The GitHub only contains the src files, needs an npm install or npm build to create the modules used in the demo. 

The Camera class and all the ML is actually from Mediapipe's toolkit. You can find out how to install their helper functions through their resources https://google.github.io/mediapipe/getting_started/javascript

**Comment by ubilrodriguez** [comment]
> mediante una etiqueta de secuencia de comandos estándar de la CDN

si les entiendo pero tengo una duda, bueno en NPM se instalar la siguiente manera (npm install kalidokit)

pero en la manera de mediante una etiqueta de secuencia de comandos estándar de la CDN. ¿Como se importar?

porque ha actualizado los codigos en el script, por cuando quiero descargar las despetencias con (npm install) me sale este error

C: \ kalidokit-main> instalación de npm

> kalidokit@1.1.2 preparar
> npm ejecutar compilación


> kalidokit@1.1.2 preconstrucción
> rm -rf dist lib

"rm" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
npm ERR! codigo 1
npm ERR! ruta C: \ kalidokit-main
npm ERR! Error de comando
npm ERR! comando C: \ WINDOWS \ system32 \ cmd.exe / d / s / c npm ejecutar compilación

npm ERR! Puede encontrar un registro completo de esta ejecución en:
npm ERR! C: \ Users \ LENOVO \ AppData \ Local \ npm-cache \ _logs \ 2021-12-16T09_07_28_650Z-debug.log

**Comment by ubilrodriguez** [comment]
> Como dijo Alen. Esta es una biblioteca destinada a ser importada a través de NPM o mediante una etiqueta de secuencia de comandos estándar de la CDN. Esto se escribió en JavaScript simple y luego se migró a Typecript. Lo instala y lo usa como cualquier otra biblioteca de JavaScript de terceros.

if I understand them but I have a question, well in NPM it is installed as follows (npm install kalidokit)

but in the way of using a standard CDN script tag. How do i import?

because it has updated the codes in the script, for when I want to download the requests with (npm install) I get this error

**Comment by ubilrodriguez** [comment]
because before in the script.js file it was like this:
const remap = Kalidokit.Utils.remap;
const clamp = Kalidokit.Utils.clamp;
const lerp = Kalidokit.Vector.lerp;

but now you have changed them into:
import * as Kalidokit from "../dist/kalidokit.es";
import * as THREE from "../dist/three";
import {GLTFLoader} from "../dist/GLTFLoader.js";
import {OrbitControls} from "three / examples / jsm / controls / OrbitControls";
import {VRM, VRMSchema, VRMUtils} from "@ pixiv / three-vrm";

for that reason they did not let me import the functions but now I have problems in exercising

**Comment by AlenSaito1** [comment]
> Excuse me, is your project developed in react and laravel? Or else in what exactly framework is it developed?

@ubilrodriguez are you referring to isekai? If so, it is built on Next.js with React.

**Comment by ubilrodriguez** [comment]
> isekai

Well they asked him about the code of the project in which he is desalted? but not isekai, what is the 3d drawing if I'm not wrong?

**Comment by ubilrodriguez** [comment]
But my big problem when I want to import or export a function from the script.js file, the 3d drawing no longer appears.
some of you know why?

**Comment by yeemachine** [comment]
Again, you should not be importing any code from the script.js file. It is just example code. Everything you need calculation wise should be come from NPM or the KalidoKit.umd.js file. 

Any questions on how to render landmark guides should really be asked on Stackoverflow or the Mediapipe repo as they are not written by us.

**Comment by ubilrodriguez** [comment]
> Nuevamente, no debería importar ningún código del archivo script.js. Es solo un código de ejemplo. Todo lo que necesita en cuanto al cálculo debe ser de NPM o del archivo KalidoKit.umd.js.
> 
> Cualquier pregunta sobre cómo renderizar guías de puntos de referencia realmente debe hacerse en Stackoverflow o en el repositorio de Mediapipe, ya que no las escribimos nosotros.

Ok I understand it, but you cannot reuse the script.js file, since from script.js I can load the VRM and also turn off the camera, everything can be done from script.js.

my question is: why can't the script.js file be reused?

**Comment by yeemachine** [comment]
I would suggest taking look at the glitch examples for a simple idea of how to use this library. It is identical to the ones found in the docs folder. Scripts are imported from index.html. 

https://glitch.com/edit/#!/kalidokit

**Comment by ubilrodriguez** [comment]
> Sugeriría echar un vistazo a los ejemplos de fallas para tener una idea simple de cómo usar esta biblioteca. Los scripts se importan de index.html.
> 
> https://glitch.com/edit/#!/kalidokit

good in my opinion is that the script.js file had a script.ts file and it was converted to the script.js file.
if so, can you publish the script.ts file, like the other .ts files? please.

**Comment by yeemachine** [comment]
Script.js was just written in JS. There is no .ts file it was compiled from. 

I will be closing this issue since we've strayed a bit off topic and it doesn't affect the use of the library itself.
