### ISSUE TITLE
Prebuild script fails on Windows

### ISSUE THREAD

**Issue by Renpona** [yeemachine/kalidokit#19]
Both building and testing fail on Windows due to the presence of a prebuild script including "rm -rf".

Windows does not necessarily have rm available, and if rm is not available, the prebuild script will fail and halt the build/run task.

It's not really a blocking issue for me since it doesn't look too difficult to workaround, but something to be aware of.

```
> Executing task: npm run test <


> kalidokit@1.1.2 test C:\Projects\Programming\kalidokit
> npm run build && npm run dev


> kalidokit@1.1.2 prebuild C:\Projects\Programming\kalidokit
> rm -rf dist lib

'rm' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kalidokit@1.1.2 prebuild: `rm -rf dist lib`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kalidokit@1.1.2 prebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by yad1d1** [comment]
Hello, you can use cmder (base ConEmu) to solve this problem. After installing cmder, run `npm run test` through this terminal tool, because it comes with the linux commands you are missing above, but it solves this problem Later, you may also encounter a node vite module problem.
