### ISSUE TITLE
[Failed to `npm run test`] "error when starting dev server: / Error: The following dependencies are imported but could not be resolved:"

### ISSUE THREAD

**Issue by yad1d1** [yeemachine/kalidokit#22]
When I run `npm run test`, I encountered an error。My node version is v14.18.2
![1](https://user-images.githubusercontent.com/35857939/146883133-b89e3c5e-f044-4227-aac7-33e0b5ad0b66.jpg)

**Comment by yeemachine** [comment]
Thanks for the report. Was a url directory issue. Should be fixed with this commit a564c5d

**Comment by yad1d1** [comment]
Thank your answer ver much  😀, But I check my `/docs/index.html`, it is right, no need to modify.  @yeemachine 
![2](https://user-images.githubusercontent.com/35857939/146886934-7b0696dc-243d-4f91-ae49-d2444dd89c27.jpg)

**Comment by yeemachine** [comment]
The incorrect script path can be found in the index.html found in the Live2D folder, which was throwing the error. Should be fixed now though.

**Comment by yad1d1** [comment]
Thank you, the problem is solved, thank you for your help。😀😀😀.
