### ISSUE TITLE
extraneous dependencies

### ISSUE THREAD

**Issue by vladmandic** [yeemachine/kalidokit#26]
currently `kalidokit` package has following hard dependencies:

```json
    "dependencies": {
        "@mediapipe/camera_utils": "^0.3.1632432234",
        "@mediapipe/drawing_utils": "^0.3.1620248257",
        "@mediapipe/holistic": "^0.5.1635989137",
        "@pixiv/three-vrm": "^0.6.7",
        "three": "^0.133.0"
    },
```

which means they will all be installed when installing `kalidokit` which makes it at least 100x bigger than it should be

and in reality, **all** of those dependencies are needed only for demos and not needed at all for actual solver.
please remove hard dependencies - you can make them optional instead

for example, i prefer to use my own implementation of ml processing (using different `mediapipe` models and using custom processing instead of `mediapipe` official modules) and using `babylonjs` instead of `threejs`

**Comment by AlenSaito1** [comment]
Kalidokit has zero dependencies. Maybe these are from some other project?

https://github.com/yeemachine/kalidokit/blob/1e44d58069c72ec76a77e05dad29212f7f39c176/package.json#L1-L51

**Comment by yeemachine** [comment]
I think @vladmandic may be referring to the version on npm. Which was slightly behind the one here on github. I've just pushed a new version out that should remove those dependencies.

**Comment by vladmandic** [comment]
@yeemachine yes, thats exactly it - thanks!  

closing as resolved
