### ISSUE TITLE
Blender integration?

### ISSUE THREAD

**Issue by VinnyVicious** [yeemachine/kalidokit#3]
Would it be possible to integrate this project with Blender and use the recorded movements as animation tracks?

**Comment by yeemachine** [comment]
It's definitely possible. KalidoKit is a calculator, so it will give you rotation and blendshape values per frame. You could probably write something that records those frame by frame values into whatever format you want.

**Comment by GuangyuZhan** [comment]
更多的VRM模型怎么找
