### ISSUE TITLE
Failed to acquire camera feed

### ISSUE THREAD

**Issue by Minionflo** [yeemachine/kalidokit#34]
when i open the site (selfhosted) i get the error: `Failed to acquire camera feed: AbortError: Starting videoinput failed`
I tested it with Firefox.
In chrome i get the error: `Failed to acquire camera feed: NotReadableError: Could not start video source`

**Comment by ButzYung** [comment]
The function to request camera feed (MediaDevices.getUserMedia) is available only in secure contexts (HTTPS), which is not the case for most localhost setup.

**Comment by Minionflo** [comment]
with the prehosted version i get the error: `Please allow camera for facial tracking.`. I have allow access to the right camera

**Comment by Minionflo** [comment]
i have fixed it by reselecting the camera and clearing the cookies and the site data

**Comment by Minionflo** [comment]
> The function to request camera feed (MediaDevices.getUserMedia) is available only in secure contexts (HTTPS), which is not the case for most localhost setup.

It worked without HTTPS
