### ISSUE TITLE
计算与赋值思路修改建议

### ISSUE THREAD

**Issue by galigaligo** [yeemachine/kalidokit#37]
代码中，骨骼旋转主要通过Vector.findRotation 获得了与三轴的角度向量，
后面将三个角度直接赋值给了ThreeJS的欧拉角，
这个思路不对，欧拉角  != 三轴角度！！

我试试重写，梳理下思路：
1、先获得VRM或任意骨骼动画角色的骨骼初识位置，获得关键骨骼初始向量；
2、通过mediapipe获得其目标坐标，与目标向量；
3、求出两向量夹角，与其形成平面的法向量；
4、以法向量为轴，夹角为转角，形成四元数，对threejs进行赋值；

我先试试，如果成功了，再分享代码！

**Comment by satawait** [comment]
请问成功了吗？
