### ISSUE TITLE
Option to change background and cartoon character

### ISSUE THREAD

**Issue by CheungBH** [yeemachine/kalidokit#39]
Hello. Are there any options to change cartoon character or a background?

**Comment by xys20071111** [comment]
Kalidotkit is a calculator, you should set background in Three.js or Pixi.js

**Comment by yeemachine** [comment]
If you are a newcomer with JS, I would recommend taking a look at how to set up a basic scene in Three.js or Pixi.js. They have pretty good documentation and examples on their websites. 

I would also suggest not using Github repo in your projects, and instead rely on a CDN script tag or an NPM module. There will prob be less system compatibility issues if you develop using KalidoKit as a library. In the README, I also have 2 barebones examples for both Live2D and VRM on Glitch. That can also be a good starting point.

**Comment by CheungBH** [comment]
> 

Thank you. I will start learning it.
Also, I noticed that you have different cartoon characters in your demo. I wonder how to activate the other characters? Are there any option to choose them?

**Comment by yeemachine** [comment]
Characters in the demo are loaded by URL. Please refer to the glitch templates for specific implementations. 

KalidoKit only provides calculations and does not handle rendering. Please reach out to other libraries for additional questions.

**Comment by CheungBH** [comment]
Thank you for your reply.
Could you please provide the source of your current character? I may download other characters and try it myself

**Comment by xys20071111** [comment]
You can download model from VRoid Hub

**Comment by yeemachine** [comment]
Furthermore, I've listed all the links to the models I use from Vroid Hub on [Kalidoface](https://3d.kalidoface.com). It's the last info card.

**Comment by CheungBH** [comment]
> Furthermore, I've listed all the links to the models I use from Vroid Hub on [Kalidoface](https://3d.kalidoface.com). It's the last info card.

@yeemachine @xys20071111 Thanks for your kind reply. I successfully in changing the characters

**Comment by CheungBH** [comment]
> Kalidotkit is a calculator, you should set background in Three.js or Pixi.js

Another problem. Where can I find the "Three.js" or "Pixi.js"? I cannot find it in the project files

**Comment by xys20071111** [comment]
> 

They are included by <script> tag in the index.html
