### ISSUE TITLE
Hand movement towards body

### ISSUE THREAD

**Issue by chris-aeviator** [yeemachine/kalidokit#4]
hi – amazing project!

I realized that movements towards my body are not possible, though the skeleton view predicts it correctly – is this a general limitation with how the avatar is drawn?

**Comment by yeemachine** [comment]
Hi!

Yup that is a known issue. Primarily with how the vector math is calculated to derive those skeleton rotations. Definitely open  to contributions if anyone has ideas on the proper formula!

**Comment by ButzYung** [comment]
@chris-aeviator Do you mean movements relative to the camera (e.g. walking towards/away from the camera)?
