### ISSUE TITLE
[NEED HELP]: Why use screen space coordinates to calculate Euler angles?

### ISSUE THREAD

**Issue by DefTruth** [yeemachine/kalidokit#42]
Hi ~ Thanks for your great work ! i have encounter some problems when reading your source code. The main confusion is that the output landmarks from mediapipe FaceMesh is in Screen Coordinates as mention at [face_mesh#face-transform-module](https://google.github.io/mediapipe/solutions/face_mesh#face-transform-module), but you have use these landmarks to calculate Euler angles in your `rollPitchYaw` method. The pipeline for FaceSolver is look like:  
```text
scree coords 3D landmarks -> multiply imagesize(still screen coords) -> calcHead() -> rollPitchYaw() use scree coords
```  
The landmarks detected by mediapipe is not in World Space nor Model Space, I just can not understand the calculation logic about the pipeline above. Can you tell me why this is valid? It will make a great help to me, many thanks ~

**Comment by yeemachine** [comment]
Facemesh uses parallel projection with their coordinates, where the Z axis is scaled similarly to the X axis. You can read more about the methodology on Mediapipe's website.

And it turns out that it is "good enough" to calculate 180deg of freedom rotation.

**Comment by DefTruth** [comment]
thanks~
