### ISSUE TITLE
Using other Pose Trackers instead of MediaPipe

### ISSUE THREAD

**Issue by Shreeshail-Hingane** [yeemachine/kalidokit#44]
Is there any particular reason to use MediaPipe? Why not use another method like [VIBE](https://github.com/mkocabas/VIBE), which directly gives output in the format of 3D rotation data for joints (instead of 3D Cartesian coordinates like MediaPipe). This way, there wouldn't be the need to perform the complex kinematic calculations which is the majority of the code of this kalidokit library.

**Comment by ButzYung** [comment]
VIBE doesn't work on browser/JavaScript I suppose?

**Comment by Shreeshail-Hingane** [comment]
I see. Thanks.
