### ISSUE TITLE
Calling the Solver from node.js

### ISSUE THREAD

**Issue by FishWoWater** [yeemachine/kalidokit#63]
Hi, thanks for your awesome project!

I am wondering whether it's possible to calling the kalidokit face solver from a node.js service. 

The story:    a windows executable(exe) send an image to a nodejs web service, which runs mediapipe and kalidokit

Can you give me some suggestions?

Thanks!

**Comment by xys20071111** [comment]
以前试过在python里用mediapipe捕获，然后把点传给nodejs，没试过直接传图片

**Comment by FishWoWater** [comment]
@xys20071111 可以分享下您的nodejs代码吗

**Comment by xys20071111** [comment]
```
import net from 'net'
import { Face, Pose } from 'kalidokit'

interface IPoint {
    x: number
    y: number
    z: number
    visibility: number
}

interface IData {
    'poseLandmarks':  Array<IPoint>
    'worldPoseLandmarks':  Array<IPoint>
    'rightHandLandmarks':  Array<IPoint>
    'leftHandLandmarks':  Array<IPoint>
    'faceLandmarks': Array<IPoint>
}

const client = net.connect({
    host: '127.0.0.1',
    port: 6354
})

setInterval(() => {
    client.write('next')
}, 500)

client.on('data', (rawData) => {
    const length = rawData.readInt32LE(0)
    const dataString = rawData.subarray(4).toString()
    if (dataString.length === length) {
        const data: IData = JSON.parse(dataString)
        if (data.faceLandmarks.length > 0) {
            console.log(Face.solve(data.faceLandmarks, {
                runtime: 'mediapipe',
                imageSize: { width: 640, height: 480 },
                smoothBlink: true
            }))
        }
        if (data.poseLandmarks.length > 0) {
            console.log(Pose.solve(data.worldPoseLandmarks, data.poseLandmarks, {
                runtime: 'mediapipe',
                imageSize: { width: 640, height: 480 }
            }))
        }
    }
})
```
不过需要自己把kalidokit的tsconfig.json中的`"module": "es6"`改成`"module": "CommonJS"`，然后编译出来

**Comment by FishWoWater** [comment]
@xys20071111 能加下您联系方式吗, 有偿咨询您一下~ 因为我之前没接触过前端，好多概念/框架/逻辑不懂

**Comment by xys20071111** [comment]
抱歉，我自己对这方面也不懂，纯粹是出于兴趣爱好在玩

**Comment by FishWoWater** [comment]
@xys20071111 
好吧，还是感谢您!
您刚给的代码应该是 作为服务器监听python客户端传过来的mediapipe数据的代码么
请问下可以分享一下完整的服务端代码吗，主要是一些配置文件和项目工程我不太懂, 比如这个是ts吧，里面的`net`是什么库?
我理解一下思路，
1. git clone https://github.com/yeemachine/kalidokit
2. cd kalidolit 
3. # change es6 to commonjs 
4. npm run build:lib
这个时候应该是在 dist/下编译好了commonjs module, 要怎么在服务端引用进来呢，服务端引用的不是重新 `npm install kalidokit`的吗

感谢！！

**Comment by xys20071111** [comment]
服务端的代码：https://github.com/xys20071111/3DPose  
`npm run build:lib` 之后运行 `npm pack`,会生成一个 `kalidokit-1.1.5.tgz`，之后在你的项目里`npm install /path/to/kalidokit-1.1.5.tgz`  
net是nodejs自带的网络库，在后端运行，在这里用来连接到python服务端，监听数据

**Comment by FishWoWater** [comment]
@xys20071111 太感谢啦!!! 我研究一下您的代码

**Comment by FishWoWater** [comment]
我按您说的操作了, python端我没问题，就是js端有错误，这个是我的操作流程

1. mkdir tscode
2. cd tscode && npm init && npm install --save-dev typescript 
3. 把您上面给的代码写入到文件 index.ts 中  ---part1
4. cd .. && git clone https://github.com/yeemachine/kalidokit && cd kalidokit
5. change "module"： “es6" => "module": "CommonJS"
6. npm install (这里包含了npm run build:lib)
7. npm pack && cp kalidokit-1.1.5.tgz tscode 
8. cd tscode && npm install kalidokit-1.1.5.tgz  ---part2
9. tsc index.ts  

我理解的是需要把`index.ts`编译成`js` 再`node index.js`， 但是我这里报错了
![image](https://user-images.githubusercontent.com/37951601/194809815-cf12533f-4527-435a-b25e-2eac63d195eb.png)


这个是我生成的index.js的代码
```
"use strict";
exports.__esModule = true;
var net_1 = require("net");
var kalidokit_1 = require("kalidokit");
var client = net_1["default"].connect({
    host: '127.0.0.1',
    port: 6354
});
setInterval(function () {
    client.write('next');
}, 500);
client.on('data', function (rawData) {
    var length = rawData.readInt32LE(0);
    var dataString = rawData.subarray(4).toString();
    if (dataString.length === length) {
        var data = JSON.parse(dataString);
        if (data.faceLandmarks.length > 0) {
            console.log(kalidokit_1.Face.solve(data.faceLandmarks, {
                runtime: 'mediapipe',
                imageSize: { width: 640, height: 480 },
                smoothBlink: true
            }));
        }
        if (data.poseLandmarks.length > 0) {
            console.log(kalidokit_1.Pose.solve(data.worldPoseLandmarks, data.poseLandmarks, {
                runtime: 'mediapipe',
                imageSize: { width: 640, height: 480 }
            }));
        }
    }
});

```

直接运行的话报错
![image](https://user-images.githubusercontent.com/37951601/194809952-165fcfc7-df4c-4844-b28d-55f4ff84bad0.png)

**Comment by xys20071111** [comment]
这个问题我没遇到过，可能是没有`tsc --init`导致的吧  
我把我nodejs的部分整个发给你吧  
[kalidokit-nodejs.zip](https://github.com/yeemachine/kalidokit/files/9743789/kalidokit-nodejs.zip)

**Comment by FishWoWater** [comment]
@xys20071111 谢谢! 已经解决啦，我`npm start` (`tsc -p . && node dist/index.js`)来跑就对了

: )
