### ISSUE TITLE
Question about calculation of hips and solver

### ISSUE THREAD

**Issue by seastar105** [yeemachine/kalidokit#65]
Thanks for nice repo. I'm trying to move avatar from camera input and mediapipe's holistic in unity now by porting kalidokit's solver. Here's some questiong

https://github.com/yeemachine/kalidokit/blob/c720d483df867996be96e2c3218e963da9190ecf/src/PoseSolver/calcHips.ts#L12-L19

why using fraction 1 in lerp to  calculate center of two points? isn't it 0.5?

secondly, it seems mediapipe and three.js are using right-handed coordinate, but unity is using left-handed coordinate. So would it be okay to simply porting kalidokit's logic to C# unity? Actually, it's not working right now sadly. 

Finally, pose solver always returns hips' position with y=0. could you explain why?

**Comment by yeemachine** [comment]
You're right. The hips coordinates should be using .5 instead of 1 for the normalization.

As for the integration with Unity, you would likely need to retarget the rotation axis to fit Unity's coordinate system.
