### ISSUE TITLE
Is there any documentation for React integration

### ISSUE THREAD

**Issue by Cybermage83** [yeemachine/kalidokit#9]
I am sure, i can figure out how to integrate this into React. But i was wondering if there is any code i may find somewhere for simplicity sake?

Thank you.

Love you work.

**Comment by yeemachine** [comment]
Sadly this is not something I'm that experienced in. However, a contributor did end up making this to React app test for his Typescript migration of KalidoKit. Hope that helps!
https://github.com/alensaito1/isekai

**Comment by minhkhue3214** [comment]
@Cybermage83 Have you found any solutions for that ?

**Comment by Cybermage83** [comment]
sort of yes, through trial and error
